G-code: make make_fcp_x3g more modular, properly capture stderr of all scripts, and abort if any of them fails.

diff --git a/make_fcp_x3g b/make_fcp_x3g
--- a/make_fcp_x3g
+++ b/make_fcp_x3g
@@ -2,16 +2,16 @@
 # Does post-processing on G-code files generated by Slic3r, assuming it has been
 # configured with my custom G-code snippets.
 # 1. Runs the dualstrusion post-processing script if the file has the start
-#    G-code for this script. You can find this script at:
-#    https://www.dr-lex.be/info-stuff/print3d-dualstrusion.html
+#    G-code for this script.
 # 2. Fixes incorrect temperature command for single extrusion prints.
-# 3. Optionally applies my retraction improver hack.
-# 4. Sends the G-code file through GPX to produce an x3g file.
+# 3. Optionally runs the MightyVariableFan PWM post-processing script.
+# 4. Optionally applies my retraction improver hack.
+# 5. Sends the G-code file through GPX to produce an x3g file.
 # Should be called with only a single argument: the G-code file.
 # To disable all post-processing scripts and merely invoke GPX, add '-P' as
 #   first argument.
 #
-# Version: 20180325
+# Version: 20180618
 # Alexander Thomas a.k.a. DrLex, https://www.dr-lex.be/
 # Released under Creative Commons Attribution 4.0 International license.
 
@@ -22,10 +22,11 @@
 GPX=/usr/local/bin/gpx
 
 # The following settings are optional and will be silently ignored if the paths
-# do not point to executable files. You don't need to explicitly comment them
+# do not point to *executable* files. You don't need to explicitly comment them
 # out if you're not using these extra post-processing scripts.
 
-# Path to the executable dualstrusion post-processing script.
+# Path to the dualstrusion post-processing script.
+# See https://github.com/DrLex0/DualstrusionPostproc for more information.
 DUALSTRUDE_SCRIPT=/Users/athomas/bin/dualstrusion-postproc.pl
 
 # Path to the PWM postprocessor script in case you would be using my slightly
@@ -61,6 +62,7 @@ function usage
 	echo "  -k: keep copy of original file."
 }
 
+
 while getopts ':hPpk' opt; do
 	case $opt in
 		h)
@@ -77,7 +79,7 @@ while getopts ':hPpk' opt; do
 			KEEP_ORIG=1
 			;;
 		\?)
-			echo "Ignoring unknown option: -$OPTARG" >&2
+			echo "Ignoring unknown option: -${OPTARG}" >&2
 			;;
 	esac
 done
@@ -89,36 +91,56 @@ if [ -z "$1" ]; then
 	exit 2
 fi
 
-if [ -n "$EXTRA_PATH" ]; then
-	export PATH=$(awk "{ sub(/:\/usr\/bin:/, \":${EXTRA_PATH}:/usr/bin:\"); print }" <<< "$PATH")
+if [ -n "${EXTRA_PATH}" ]; then
+	export PATH=$(echo "${PATH}" | awk "{ sub(/:\/usr\/bin:/, \":${EXTRA_PATH}:/usr/bin:\"); print }")
 fi
 
 arg_p=''
 # Do not use sed, sed in OS X stinks.
 origfile=$(echo "$1" | perl -pe 's/\.gcode$/_orig.gcode/i')
+stripped=$(echo "$1" | perl -pe 's/\.gcode$//i')
+warn_file="${stripped}.WARN.txt"
+fail_file="${stripped}.FAIL.txt"
 
-if [ -z "$no_postproc" ]; then
-	stripped=$(echo "$1" | perl -pe 's/\.gcode$//i')
-	warn_file="${stripped}.WARN.txt"
-	rm -f "$warn_file"
+function run_script
+{
+	# Runs a script that prints processed G-code on standard output. If the script exits with an
+	# error code, stderr will be written to $fail_file, otherwise anything appearing on stderr is
+	# written to $warn_file. The original gcode file is overwritten.
+	local name=$1
+	local script=$2
+	local gcode=$3
+	local extra_args=$4
 
-	if [ "$KEEP_ORIG" == "1" ]; then
+	local tempfile warnings
+
+	echo "Running ${name} script..."
+	tempfile=$(mktemp)
+	# capture stdout to a file and stderr to a variable
+	warnings=$("${script}" $extra_args "${gcode}" 2>&1 >"${tempfile}")
+	if [ $? != 0 ] ; then
+		if [ -z "${warnings}" ]; then
+			warnings="The ${name} script failed, but without any output on stderr."
+		fi
+		echo "${warnings}" >> "${fail_file}"
+		echo "${warnings}" >&2
+		rm -f "${tempfile}"
+		exit 1
+	fi
+	[ -n "${warnings}" ] && echo "${warnings}" >> "${warn_file}"
+	mv "${tempfile}" "${gcode}"
+	chmod 644 "${gcode}"
+}
+
+if [ -z "${no_postproc}" ]; then
+	rm -f "${warn_file}" "${fail_file}"
+
+	if [ "${KEEP_ORIG}" == "1" ]; then
 		cp -p "$1" "${origfile}"
 	fi
-	if [ -x "$DUALSTRUDE_SCRIPT" ] && grep -q 'FOR USE IN COMBINATION WITH DUALSTRUSION POST-PROCESSING SCRIPT .*ONLY' "$1" 2>/dev/null; then
-		# Post-process the file with the magical dualstrusion enhancer script.
-		echo "Post-processing dualstrusion file..."
-		tempfile=$(mktemp)
-		tempfail=$(mktemp)
-		if ! "${DUALSTRUDE_SCRIPT}" "$1" > "${tempfile}" 2> "${tempfail}"; then
-			rm -f "${tempfile}"
-			chmod 644 "${tempfail}"
-			mv "${tempfail}" "$1-FAIL.txt"
-			exit 1
-		fi
-		rm -f "${tempfail}"
-		mv "${tempfile}" "$1"
-		chmod 644 "$1"
+
+	if [ -x "${DUALSTRUDE_SCRIPT}" ] && grep -q 'FOR USE IN COMBINATION WITH DUALSTRUSION POST-PROCESSING SCRIPT .*ONLY' "$1" 2>/dev/null; then
+		run_script 'dualstrusion' "${DUALSTRUDE_SCRIPT}" "$1"
 	elif grep -qE ';- - - Custom G-code for (left|right) extruder printing' "$1" 2>/dev/null; then
 		# Work around bug in Slic3r that always causes T0 to be heated if the second layer has a
 		# different filament temperature. See https://github.com/alexrj/Slic3r/issues/4003
@@ -139,20 +161,12 @@ if [ -z "$no_postproc" ]; then
 		rm -f "$1.trashme"
 	fi
 
-	if [ -x "$RETRACT_SCRIPT" ]; then
-		warnings=$($RETRACT_SCRIPT "$1" 2>&1 >"$1.postproc")  # capture stdout to a file and stderr to a variable
-		mv -f "$1.postproc" "$1"
-		if [ -n "${warnings}" ]; then
-			echo "${warnings}" >> "$warn_file"
-		fi
+	if [ -x "${RETRACT_SCRIPT}" ]; then
+		run_script 'retraction' "${RETRACT_SCRIPT}" "$1"
 	fi
 
-	if [ -x "$PWM_SCRIPT" ]; then
-		warnings=$($PWM_SCRIPT -o "$1.postproc" "$1" 2>&1)  # capture stderr to a variable
-		mv -f "$1.postproc" "$1"
-		if [ -n "${warnings}" ]; then
-			echo "${warnings}" >> "$warn_file"
-		fi
+	if [ -x "${PWM_SCRIPT}" ]; then
+		run_script 'fan PWM post-processing' "${PWM_SCRIPT}" "$1"
 	fi
 
 	# -p overrides % display with something that better approximates total print time than merely
@@ -163,7 +177,7 @@ if [ -z "$no_postproc" ]; then
 	arg_p=' -p'
 fi
 
-if [ -n "$force_progress" ]; then
+if [ -n "${force_progress}" ]; then
 	arg_p=' -p'
 fi
 
